name: Autobuild
# modified from https://github.com/nosoop/NinjaBuild-SMPlugin/blob/master/contrib/github-workflow/build-on-version-tag-push.yml

on:
  push:
    tags:
    - 'v*'

jobs:
  run:
    name: Run action
    runs-on: ubuntu-latest

    # skip build on '[ci skip]'
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: "1.12.x"

    - name: Compile plugins
      run: |
        cd ./scripting
        pwd
        spcomp -i"./include/" giveaways.sp -o ../plugins/giveaways.smx
        ls -la

    - name: Zip packages
      run: |
        mkdir build
        7za a -r build/giveaways.zip addons/ sound/
        ls -la
        pwd

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./build/giveaways.zip
        fail_on_unmatched_files: true
        generate_release_notes: true
        # if: contains(github.ref, 'beta')
        # prerelease: true
